export const menus = [
  {
    image: "https://source.unsplash.com/random/chimera",
    title: "Croissant Butter Cream",
    price: 18000,
    link: "/pages/menu/detail.html",
  },
  {
    image: "https://source.unsplash.com/random/bee",
    title: "Croissant Butter Cream",
    price: 11000,
    link: "/pages/menu/detail.html",
  },
  {
    image: "https://source.unsplash.com/random/ant",
    title: "Croissant Butter Cream",
    price: 8000,
    link: "/pages/menu/detail.html",
  },
  {
    image: "https://source.unsplash.com/random/antlion",
    title: "Croissant Butter Cream",
    price: 16000,
    link: "/pages/menu/detail.html",
  },
  {
    image: "https://source.unsplash.com/random/band",
    title: "Croissant Butter Cream",
    price: 7000,
    link: "/pages/menu/detail.html",
  },
  {
    image: "https://source.unsplash.com/random/rock",
    title: "Croissant Butter Cream",
    price: 7500,
    link: "/pages/menu/detail.html",
  },
  {
    image: "https://source.unsplash.com/random/drum",
    title: "Croissant Butter Cream",
    price: 9900,
    link: "/pages/menu/detail.html",
  },
  {
    image: "https://source.unsplash.com/random/snare",
    title: "Croissant Butter Cream",
    price: 18000,
    link: "/pages/menu/detail.html",
  },
  {
    image: "https://source.unsplash.com/random/guitar",
    title: "Croissant Butter Cream",
    price: 2500,
    link: "/pages/menu/detail.html",
  },
  {
    image: "https://source.unsplash.com/random/piano",
    title: "Croissant Butter Cream",
    price: 89000,
    link: "/pages/menu/detail.html",
  },
  {
    image: "https://source.unsplash.com/random/keyboard",
    title: "Croissant Butter Cream",
    price: 45000,
    link: "/pages/menu/detail.html",
  },
  {
    image: "https://source.unsplash.com/random/violin",
    title: "Croissant Butter Cream",
    price: 5500,
    link: "/pages/menu/detail.html",
  },
  {
    image: "https://source.unsplash.com/random/bass",
    title: "Croissant Butter Cream",
    price: 5000,
    link: "/pages/menu/detail.html",
  },
  {
    image: "https://source.unsplash.com/random/triumphet",
    title: "Croissant Butter Cream",
    price: 13000,
    link: "/pages/menu/detail.html",
  },
  {
    image: "https://source.unsplash.com/random/joox",
    title: "Croissant Butter Cream",
    price: 31000,
    link: "/pages/menu/detail.html",
  },
  {
    image: "https://source.unsplash.com/random/spotify",
    title: "Croissant Butter Cream",
    price: 45000,
    link: "/pages/menu/detail.html",
  },
  {
    image: "https://source.unsplash.com/random/youtube",
    title: "Croissant Butter Cream",
    price: 4000,
    link: "/pages/menu/detail.html",
  },
  {
    image: "https://source.unsplash.com/random/google",
    title: "Croissant Butter Cream",
    price: 21000,
    link: "/pages/menu/detail.html",
  },
  {
    image: "https://source.unsplash.com/random/yahoo",
    title: "Croissant Butter Cream",
    price: 35000,
    link: "/pages/menu/detail.html",
  },
  {
    image: "https://source.unsplash.com/random/facebook",
    title: "Croissant Butter Cream",
    price: 2000,
    link: "/pages/menu/detail.html",
  },
  {
    image: "https://source.unsplash.com/random/twitter",
    title: "Croissant Butter Cream",
    price: 10500,
    link: "/pages/menu/detail.html",
  },
  {
    image: "https://source.unsplash.com/random/instagram",
    title: "Croissant Butter Cream",
    price: 10000,
    link: "/pages/menu/detail.html",
  },
];
